---
resources:
  - name: concourse-pytest
    type: git
    icon: github
    check_every: 30m
    source:
      uri: https://github.com/95rade/pytest-tutorial
      branch: main

  - name: slack-alert
    type: slack-notification
    icon: slack
    source:
      url: ((slack-webhook))

resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: v1.3.0

jobs:
  - name: install-dependancies
    plan:
      - get: concourse-pytest
        trigger: true
      - task: install-dependancies
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: python}
          inputs:
            - name: concourse-pytest
          outputs: 
            - name: pytest-installed
          run:
            path: /bin/sh
            args:
            - -c
            - |
              pip3 install pytest pytest-xdist

  - name: run-pytest-smoke
    serial: true
    plan:
      - get: concourse-pytest
        trigger: true
        passed: [install-dependancies]
      - task: run-smoke
        config:
          platform: linux
          image_resource:
            type: docker-image
            #source: {repository: python}
            source: {repository: qnib/pytest}
          inputs:
            - name: concourse-pytest
          run:
            dir: concourse-pytest
            #path: python
            #args:
            #  - -m pytest
            path: /bin/sh
            args:
            - -c
            - |
              #pip3 install pytest pytest-xdist
              pwd
              ls -al
              python -m pytest -v test_compare.py
        on_failure:
            put: slack-alert
            params:
                channel: '#concourse'
                #username: 'rade'
                #icon_emoji: ':concourse:'    # set in slack webhook settings
                icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
                silent: true
                text: |
                      *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* ($BUILD_NAME) FAILED - Testing image failure
                      https://ci.domain.xyz/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

        on_success:
            put: slack-alert
            params:
                channel: '#concourse'
                #username: 'rade'
                #icon_emoji: ':concourse:'    # set in slack webhook settings
                icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
                silent: true
                text: |
                      *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* ($BUILD_NAME) SUCCESS - Testing image Succeeded
                      https://ci.domain.xyz/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME


  - name: run-pytest-acceptance
    serial: true
    plan:
      - get: concourse-pytest
        trigger: true
        passed: [install-dependancies]
      - task: run-acceptance
        config:
          platform: linux
          image_resource:
            type: docker-image
            #source: {repository: python}
            source: {repository: qnib/pytest}
          inputs:
            - name: concourse-pytest
          run:
            dir: concourse-pytest
            #path: python
            #args:
            #  - -m pytest
            path: /bin/sh
            args:
            - -c
            - |
              #pip3 install pytest pytest-xdist
              # no longer needed since we have pytest docker image.
              python -m pytest -v test_div_by_3_6.py::test_divisible_by_3
        on_failure:
            put: slack-alert
            params:
                channel: '#concourse'
                #username: 'rade'
                #icon_emoji: ':concourse:'    # set in slack webhook settings
                icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
                silent: true
                text: |
                      *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* ($BUILD_NAME) FAILED - Testing image failure
                      https://ci.domain.xyz/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

        on_success:
            put: slack-alert
            params:
                channel: '#concourse'
                #username: 'rade'
                #icon_emoji: ':concourse:'    # set in slack webhook settings
                icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
                silent: true
                text: |
                      *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* ($BUILD_NAME) SUCCESS - Testing image Succeeded
                      https://ci.domain.xyz/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

  
  - name: run-performance-tests
    serial: true
    plan:
      - get: concourse-pytest
        trigger: true
        passed: [run-pytest-smoke,run-pytest-acceptance]
      - task: run-performance-task
        config:
          platform: linux
          image_resource:
            type: docker-image
            #source: {repository: python}
            source: {repository: qnib/pytest}
          run:
            dir: concourse-pytest
            path: /bin/sh
            args:
            - -c
            - |
              #pip3 install pytest pytest-xdist
              # no longer needed since we have pytest docker image.
              python -m pytest --collect-only
        on_failure:
            put: slack-alert
            params:
                channel: '#concourse'
                #username: 'rade'
                #icon_emoji: ':concourse:'    # set in slack webhook settings
                icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
                silent: true
                text: |
                      *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* ($BUILD_NAME) FAILED - Testing image failure
                      https://ci.domain.xyz/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

        on_success:
            put: slack-alert
            params:
                channel: '#concourse'
                #username: 'rade'
                #icon_emoji: ':concourse:'    # set in slack webhook settings
                icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
                silent: true
                text: |
                      *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* ($BUILD_NAME) SUCCESS - Testing image Succeeded
                      https://ci.domain.xyz/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

