---
resources:
  - name: concourse-pytest
    type: git
    icon: github
    check_every: 30m
    source:
      uri: https://github.com/95rade/pytest-tutorial
      branch: main

jobs:
  - name: install-dependancies
    plan:
      - get: concourse-pytest
        trigger: true
      - task: install-dependancies
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: python}
          inputs:
            - name: concourse-pytest
          outputs: 
            - name: pytest-installed
          run:
            path: /bin/sh
            args:
            - -c
            - |
              pip3 install pytest pytest-xdist

  - name: run-pytest-smoke
    serial: true
    plan:
      - get: concourse-pytest
        trigger: true
        passed: [install-dependancies]
      - task: run-smoke
        config:
          platform: linux
          image_resource:
            type: docker-image
            #source: {repository: python}
            source: {repository: qnib/pytest}
          inputs:
            - name: concourse-pytest
          run:
            dir: concourse-pytest
            #path: python
            #args:
            #  - -m pytest
            path: /bin/sh
            args:
            - -c
            - |
              #pip3 install pytest pytest-xdist
              pwd
              ls -al
              python -m pytest -v test_compare.py

  - name: run-pytest-acceptance
    serial: true
    plan:
      - get: concourse-pytest
        trigger: true
        passed: [run-pytest-smoke]
      - task: run-acceptance
        config:
          platform: linux
          image_resource:
            type: docker-image
            #source: {repository: python}
            source: {repository: qnib/pytest}
          inputs:
            - name: concourse-pytest
          run:
            dir: concourse-pytest
            #path: python
            #args:
            #  - -m pytest
            path: /bin/sh
            args:
            - -c
            - |
              #pip3 install pytest pytest-xdist
              # no longer needed since we have pytest docker image.
              python -m pytest -v test_div_by_3_6.py